export const emojiCategories = [
  { name: 'Smileys & Emotion', icon: '😀' },
  { name: 'People & Body', icon: '👋' },
  { name: 'Animals & Nature', icon: '🐶' },
  { name: 'Food & Drink', icon: '🍔' },
  { name: 'Travel & Places', icon: '✈️' },
  { name: 'Activities', icon: '⚽' },
  { name: 'Objects', icon: '💡' },
  { name: 'Symbols', icon: '❤️' },
  { name: 'Flags', icon: '🏳️' },
];

export const emojiData = [
  // Smileys & Emotion
  { emoji: '😀', name: 'Grinning Face', category: 'Smileys & Emotion' },
  { emoji: '😃', name: 'Grinning Face with Big Eyes', category: 'Smileys & Emotion' },
  { emoji: '😄', name: 'Grinning Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { emoji: '😁', name: 'Beaming Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { emoji: '😆', name: 'Grinning Squinting Face', category: 'Smileys & Emotion' },
  { emoji: '😅', name: 'Grinning Face with Sweat', category: 'Smileys & Emotion' },
  { emoji: '🤣', name: 'Rolling on the Floor Laughing', category: 'Smileys & Emotion' },
  { emoji: '😂', name: 'Face with Tears of Joy', category: 'Smileys & Emotion' },
  { emoji: '🙂', name: 'Slightly Smiling Face', category: 'Smileys & Emotion' },
  { emoji: '🙃', name: 'Upside-Down Face', category: 'Smileys & Emotion' },

  // People & Body
  { emoji: '👋', name: 'Waving Hand', category: 'People & Body' },
  { emoji: '🤚', name: 'Raised Back of Hand', category: 'People & Body' },
  { emoji: '🖐️', name: 'Hand with Fingers Splayed', category: 'People & Body' },
  { emoji: '✋', name: 'Raised Hand', category: 'People & Body' },
  { emoji: '🖖', name: 'Vulcan Salute', category: 'People & Body' },
  { emoji: '👌', name: 'OK Hand', category: 'People & Body' },
  { emoji: '🤌', name: 'Pinched Fingers', category: 'People & Body' },
  { emoji: '🤏', name: 'Pinching Hand', category: 'People & Body' },
  { emoji: '✌️', name: 'Victory Hand', category: 'People & Body' },
  { emoji: '🤞', name: 'Crossed Fingers', category: 'People & Body' },

  // Animals & Nature
  { emoji: '🐶', name: 'Dog Face', category: 'Animals & Nature' },
  { emoji: '🐱', name: 'Cat Face', category: 'Animals & Nature' },
  { emoji: '🐭', name: 'Mouse Face', category: 'Animals & Nature' },
  { emoji: '🐹', name: 'Hamster Face', category: 'Animals & Nature' },
  { emoji: '🐰', name: 'Rabbit Face', category: 'Animals & Nature' },
  { emoji: '🦊', name: 'Fox Face', category: 'Animals & Nature' },
  { emoji: '🐻', name: 'Bear Face', category: 'Animals & Nature' },
  { emoji: '🐼', name: 'Panda Face', category: 'Animals & Nature' },
  { emoji: '🐨', name: 'Koala Face', category: 'Animals & Nature' },
  { emoji: '🐯', name: 'Tiger Face', category: 'Animals & Nature' },

  // Food & Drink
  { emoji: '🍏', name: 'Green Apple', category: 'Food & Drink' },
  { emoji: '🍎', name: 'Red Apple', category: 'Food & Drink' },
  { emoji: '🍐', name: 'Pear', category: 'Food & Drink' },
  { emoji: '🍊', name: 'Tangerine', category: 'Food & Drink' },
  { emoji: '🍋', name: 'Lemon', category: 'Food & Drink' },
  { emoji: '🍌', name: 'Banana', category: 'Food & Drink' },
  { emoji: '🍉', name: 'Watermelon', category: 'Food & Drink' },
  { emoji: '🍇', name: 'Grapes', category: 'Food & Drink' },
  { emoji: '🍓', name: 'Strawberry', category: 'Food & Drink' },
  { emoji: '🫐', name: 'Blueberries', category: 'Food & Drink' },

  // Travel & Places
  { emoji: '🚗', name: 'Car', category: 'Travel & Places' },
  { emoji: '🚕', name: 'Taxi', category: 'Travel & Places' },
  { emoji: '🚙', name: 'Sport Utility Vehicle', category: 'Travel & Places' },
  { emoji: '🚌', name: 'Bus', category: 'Travel & Places' },
  { emoji: '🚎', name: 'Trolleybus', category: 'Travel & Places' },
  { emoji: '🏎️', name: 'Racing Car', category: 'Travel & Places' },
  { emoji: '🚓', name: 'Police Car', category: 'Travel & Places' },
  { emoji: '🚑', name: 'Ambulance', category: 'Travel & Places' },
  { emoji: '🚒', name: 'Fire Engine', category: 'Travel & Places' },
  { emoji: '🚐', name: 'Minibus', category: 'Travel & Places' },

  // Activities
  { emoji: '⚽', name: 'Soccer Ball', category: 'Activities' },
  { emoji: '🏀', name: 'Basketball', category: 'Activities' },
  { emoji: '🏈', name: 'American Football', category: 'Activities' },
  { emoji: '⚾', name: 'Baseball', category: 'Activities' },
  { emoji: '🥎', name: 'Softball', category: 'Activities' },
  { emoji: '🎾', name: 'Tennis', category: 'Activities' },
  { emoji: '🏐', name: 'Volleyball', category: 'Activities' },
  { emoji: '🏉', name: 'Rugby Football', category: 'Activities' },
  { emoji: '🥏', name: 'Flying Disc', category: 'Activities' },
  { emoji: '🎱', name: 'Pool 8 Ball', category: 'Activities' },

  // Objects
  { emoji: '⌚', name: 'Watch', category: 'Objects' },
  { emoji: '📱', name: 'Mobile Phone', category: 'Objects' },
  { emoji: '💻', name: 'Laptop', category: 'Objects' },
  { emoji: '⌨️', name: 'Keyboard', category: 'Objects' },
  { emoji: '🖥️', name: 'Desktop Computer', category: 'Objects' },
  { emoji: '🖨️', name: 'Printer', category: 'Objects' },
  { emoji: '🖱️', name: 'Computer Mouse', category: 'Objects' },
  { emoji: '🖲️', name: 'Trackball', category: 'Objects' },
  { emoji: '🕹️', name: 'Joystick', category: 'Objects' },
  { emoji: '🗜️', name: 'Clamp', category: 'Objects' },

  // Symbols
  { emoji: '❤️', name: 'Red Heart', category: 'Symbols' },
  { emoji: '🧡', name: 'Orange Heart', category: 'Symbols' },
  { emoji: '💛', name: 'Yellow Heart', category: 'Symbols' },
  { emoji: '💚', name: 'Green Heart', category: 'Symbols' },
  { emoji: '💙', name: 'Blue Heart', category: 'Symbols' },
  { emoji: '💜', name: 'Purple Heart', category: 'Symbols' },
  { emoji: '🖤', name: 'Black Heart', category: 'Symbols' },
  { emoji: '🤍', name: 'White Heart', category: 'Symbols' },
  { emoji: '🤎', name: 'Brown Heart', category: 'Symbols' },
  { emoji: '💔', name: 'Broken Heart', category: 'Symbols' },

  // Flags
  { emoji: '🏳️', name: 'White Flag', category: 'Flags' },
  { emoji: '🏴', name: 'Black Flag', category: 'Flags' },
  { emoji: '🏁', name: 'Chequered Flag', category: 'Flags' },
  { emoji: '🚩', name: 'Triangular Flag', category: 'Flags' },
  { emoji: '🏳️‍🌈', name: 'Rainbow Flag', category: 'Flags' },
  { emoji: '🏳️‍⚧️', name: 'Transgender Flag', category: 'Flags' },
  { emoji: '🏴‍☠️', name: 'Pirate Flag', category: 'Flags' },
  { emoji: '🇺🇳', name: 'United Nations Flag', category: 'Flags' },
  { emoji: '🇪🇺', name: 'European Union Flag', category: 'Flags' },
  { emoji: '🇺🇸', name: 'Flag: United States', category: 'Flags' },
];

